[devobox]
image=archlinux:latest
root=false
pull=true
replace=true

# --- ISOLATION ---
home=~/devobox

# --- VOLUMES ---
volume=~/code:~/code
volume=~/.ssh:~/.ssh

# --- PACKAGES ---
additional_packages="neovim zellij lazygit git ripgrep mise starship base-devel openssh unzip curl"

# --- HOOKS ---
init_hooks="mkdir -p ~/.config"
init_hooks="[ ! -d ~/.config/nvim ] && git clone --depth 1 https://github.com/JohnAnon9771/my-nvim.git ~/.config/nvim || echo 'Nvim config ja existe'"

# zellij
init_hooks="mkdir -p ~/.config/zellij"
init_hooks="[ ! -f ~/.config/zellij/config.kdl ] && curl -fLo ~/.config/zellij/config.kdl https://raw.githubusercontent.com/JohnAnon9771/devobox/main/config/zellij.kdl || echo 'Zellij ok'"

# Starship
init_hooks="[ ! -f ~/.config/starship.toml ] && curl -fLo ~/.config/starship.toml https://raw.githubusercontent.com/JohnAnon9771/devobox/main/config/starship.toml || echo 'Starship ok'"

# --- Shell ---
init_hooks="starship init bash >> ~/.bashrc"
